### ISSUE TITLE
Remove malloc dependency

### ISSUE THREAD

**Issue by konstare** [rubenvannieuwpoort/c_unit_tests#1]
Hi,

Thank you for the nice test suite. I am just wondering is there a particular reason you keep malloc dependency in add_test function? I followed the advise from [lobste.rs](https://lobste.rs/s/qxpmad/minimalistic_c_unit_tests#c_xa8kfn) and it look like that it works see [my fork](https://github.com/konstare/c_unit_tests/blob/main/test.h).

**Comment by rubenvannieuwpoort** [comment]
Thank you for your interest and suggestion! I did not think of this; I think it's an improvement and on first sight your changes look good to me.

If you want, you can open a PR and I'll have a look at that. Otherwise I might implement this myself. Anyway, I'm not home today; I'll have a better look tomorrow.
